#!/usr/bin/env node

var rjs = require('requirejs');

rjs.optimize({
    name     : "buildy-testy",
    optimize : 'none',
    normalizeDirDefines : "skip",
    out     : function(data){
        console.log(data);
    },
    paths       : {
        "text" : "../bower_components/text/text",
        "WaxMustache" : "../bower_components/hogan/web/builds/3.0.2/hogan-3.0.2.amd"
    },
    rawText     : {
        "buildy-testy" : "define(function(require,module,exports){  return require('../get!./loader.mustache'); })"
    }
});

rjs.optimize({
    name     : "buildy-testy",
    optimize : 'none',
    normalizeDirDefines : "skip",
    out     : function(data){
        console.log(data);
    },
    paths       : {
        "text" : "../bower_components/text/text",
        "WaxMustache" : "../bower_components/mustache.js/mustache"
    },
    rawText     : {
        "buildy-testy" : "define(function(require,module,exports){  return require('../get!./loader.mustache'); })"
    }
})
